"""rename department

Revision ID: 42f46559f259
Revises: 8303b20ccd22
Create Date: 2024-08-21 05:13:50.017543

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42f46559f259'
down_revision = '8303b20ccd22'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.rename_table('department', 'departments')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.rename_table('departments', 'department')
    # ### end Alembic commands ###
